#!/bin/bash
set -e

cd "$(dirname "$0")"

wasm-pack build \
  --target no-modules \
  --out-dir ../../public/wasm \
  --release \
  --no-typescript

# Clean up unnecessary files generated by wasm-pack
rm -f ../../public/wasm/.gitignore
rm -f ../../public/wasm/package.json

echo "WASM built to packages/web/public/wasm/"
